### ISSUE TITLE
Error under python3.4

### ISSUE THREAD

**Issue by atorkhov** [google/gdata-python-client#29]
Error in python3.4:
```
>>> import atom.http_core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/dev/other/django_env3/lib/python3.4/site-packages/atom/__init__.py", line 133, in <module>
    CreateClassFromXMLString)
  File "/home/alex/dev/other/django_env3/lib/python3.4/site-packages/atom/__init__.py", line 97, in mark_deprecated
    optional_warn_function.func_name = f.func_name
AttributeError: 'function' object has no attribute 'func_name'
```

**Comment by joelfrederico** [comment]
I second this issue.

**Comment by linguinee** [comment]
I'm seeing this as well. Any updates?

**Comment by nicolasmouazan** [comment]
getting this one too. Any workaround?

**Comment by linguinee** [comment]
I changed the line to call `f.__name__`, which fixes the error. If someone could make a pull request for this fix, that'd be great.

**Comment by Savier** [comment]
Just run script 2to3 from Python/Tools/scripts something like

2to3 -w atom gdata 
(in site-packages).

**Comment by absudabsu** [comment]
still not working..

Python 3.4.2 (default, Jul  9 2015, 17:24:30) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux

> > > import gdata.youtube
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python3.4/site-packages/gdata/**init**.py", line 27, in <module>
> > >     import atom
> > >   File "/usr/lib/python3.4/site-packages/atom/**init**.py", line 133, in <module>
> > >     CreateClassFromXMLString)
> > >   File "/usr/lib/python3.4/site-packages/atom/**init**.py", line 97, in mark_deprecated
> > >     optional_warn_function.func_name = f.func_name
> > > AttributeError: 'function' object has no attribute 'func_name'

**Comment by journeytosilius** [comment]
Any solution to this ? I ran 2to3 -w atom gdata and now I can't import the libs.

**Comment by absudabsu** [comment]
i ended up using the v3 api: https://developers.google.com/youtube/v3/docs/

apparently, gdata is deprecated for youtube: https://developers.google.com/gdata/docs/directory

**Comment by journeytosilius** [comment]
yeah, me too. Using google-api-client-python.

**Comment by NerdHerd91** [comment]
Bump this is still not resolved 

``` python
    import gdata.apps.emailsettings.client
File "/usr/local/lib/python3.5/site-packages/gdata/__init__.py", line 27, in <module>
    import atom
File "/usr/local/lib/python3.5/site-packages/atom/__init__.py", line 133, in <module>
    CreateClassFromXMLString)
File "/usr/local/lib/python3.5/site-packages/atom/__init__.py", line 97, in mark_deprecated
    optional_warn_function.func_name = f.func_name
AttributeError: 'function' object has no attribute 'func_name'
```

**Comment by WinterIsComming** [comment]
Hi Any Solution ?

**Comment by Charlie37** [comment]
Hello, I second this issue :-)

**Comment by FrancoJim** [comment]
Has this been fixed yet? What other options are there to edit Google contacts without this library?

**Comment by k-funk** [comment]
@daklang It appears as though the gdata library isn't really maintained. Might look into using https://github.com/google/google-api-python-client. There also appears to be this API: https://developers.google.com/apis-explorer/?hl=en_US#p/people/v1/

**Comment by dvska** [comment]
fixed in
`pip install -e git+https://github.com/dvska/gdata-python3#egg=gdata`

**Comment by people-can-fly** [comment]
Use `f.__name__` instead of `f.func_name` in the code![bitmoji](https://render.bitstrips.com/v2/cpanel/ae3b16f4-1ec0-4f0a-b929-86bf1abc5924-f406c6a8-60d1-4b0b-a4c4-5ae92eb4a0ba-v1.png?transparent=1&palette=1&width=246)

**Comment by ghost** [comment]
Still not resolved.. can ordinary folk create a pull request?

**Comment by benjaminwhtan** [comment]
> Still not resolved.. can ordinary folk create a pull request?

There's been one since 2016, but no one with write permission has merged: https://github.com/google/gdata-python-client/pull/49
As k-funk mentioned, we could consider using https://github.com/google/google-api-python-client instead. Otherwise, best bet's probably just to fork and make the update ourselves.

**Comment by Tahirhan** [comment]
same issue

**Comment by Tahirhan** [comment]
solved with `pip3 install -e git+https://github.com/dvska/gdata-python3#egg=gdata`
